CREATE TABLE "USUARIOS" (
  "ID" NUMBER,
  "TIPO_USUARIO" VARCHAR2(255),
  "NOMBRE" VARCHAR2(255),
  "UBICACION" VARCHAR2(255),
  "LATITUD" NUMBER,
  "LONGITUD" NUMBER,
  "FOTO" VARCHAR2(255),
  "LENGUAJE (INGLES, ESPANOL)" VARCHAR2(255),
  "CODIGO_INVITACION" VARCHAR2(255),
  "EMAIL" VARCHAR2(255),
  "EMAIL_ALTERNATIVO" VARCHAR2(255),
  "TELEFONO" VARCHAR2(255),
  "LICENCIA" VARCHAR2(255),
  "CUENTA_BANCO" VARCHAR2(255),
  PRIMARY KEY ("ID")
);


CREATE TABLE "MEDIOS_DE_PAGOS" (
  "ID" NUMBER,
  "NOMBRE" VARCHAR2(255),
  PRIMARY KEY ("ID")
);

CREATE TABLE "CUIDADES" (
  "ID" NUMBER,
  "ESTADO" NUMBER,
  "NOMBRE" VARCHAR2(255),
  "PAIS" VARCHAR2(255),
  "MODEDA" VARCHAR2(255),
  PRIMARY KEY ("ID")
);

CREATE TABLE "CODIGOS_PROMOCIONALES" (
  "ID" NUMBER,
  "USUARIO_ID" NUMBER,
  "VALOR" DECIMAL,
  "ESTADO" VARCHAR2(255),
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) 
);

CREATE TABLE "VEHICULOS" (
  "ID" NUMBER,
  "USUARIO_ID" NUMBER,
  "MARCA" VARCHAR2(255),
  "PLACA" VARCHAR2(255),
  "MODELO" NUMBER,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_USUARIO_VEHICULO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) 
);

CREATE TABLE "CONDUCTOR_VEHICULOS" (
  "ID" NUMBER,
  "USUARIO_ID" NUMBER,
  "VEHICULO_ID" NUMBER,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_USUARIO_CONDUCTOR FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
  CONSTRAINT FK_VEHICULO_CONDUCTOR FOREIGN KEY (VEHICULO_ID) REFERENCES VEHICULOS(ID)
);


CREATE TABLE "SERVICIOS" (
  "ID" NUMBER,
  "FECHA_HORA_INICIO" TIMESTAMP,
  "TIPO_SERVICIO" VARCHAR2(255),
  "ESTADO" VARCHAR2(255),
  "CLIENTE_ID" NUMBER,
  "CONDUCTOR_VEHICULO_ID" NUMBER,
  "CUIDAD_ID" NUMBER,
  "DIRECCION_ORIGEN" VARCHAR2(255),
  "DIRECCION_DESTINO" VARCHAR2(255),
  "FECHA_HORA_ORIGEN" TIMESTAMP,
  "FECHA_HORA_DESTINO" TIMESTAMP,
  "TOTAL_TIEMPO" FLOAT,
  "VALOR_FINAL" FLOAT,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES USUARIOS(ID),
  CONSTRAINT FK_CONDUCTOR_VEHICULO FOREIGN KEY (CONDUCTOR_VEHICULO_ID) REFERENCES CONDUCTOR_VEHICULOS(ID),
  CONSTRAINT FK_CUIDAD FOREIGN KEY (CUIDAD_ID) REFERENCES CUIDADES(ID)
);

CREATE TABLE "UBICACIONES_SERVICIOS" (
  "ID" NUMBER,
  "SERVICIO_ID" NUMBER,
  "LATITUD" NUMBER,
  "LONGITUD" NUMBER,
  "FECHA_HORA" TIMESTAMP,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_SERVICIO FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS(ID) 
);

CREATE TABLE "FACTURAS" (
  "ID" NUMBER,
  "FECHA" TIMESTAMP,
  "SERVICIO_ID" NUMBER,
  "CLIENTE_ID" NUMBER,
  "VALOR_TOTAL" DECIMAL,
  "LIQUIDADO" NUMBER(1),
  "VALOR" DECIMAL,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_SERVICIO_FACTURA FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIOS(ID),
  CONSTRAINT FK_CLIENTE_ID_FACTURA FOREIGN KEY (CLIENTE_ID) REFERENCES USUARIOS(ID)  
);

CREATE TABLE "USUARIOS_MEDIOS_DE_PAGOS" (
  "ID" NUMBER,
  "USUARIO_ID" NUMBER,
  "MEDIO_PAGO_ID" NUMBER,  
  "EMAIL" VARCHAR2(255),
  "ENVIAR_CORREO" NUMBER(1),
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_MEDIO_PAGO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
  CONSTRAINT FK_MEDIO_PAGO_MEDIO_PAGO FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES MEDIOS_DE_PAGOS(ID),
  CONSTRAINT FK_CUENTA_EMPRESARIAL FOREIGN KEY (CUENTA_EMPRESARIAL_ID) REFERENCES CUENTAS_TARJETAS(ID) 
);

CREATE TABLE "TARJETAS_DE_CREDITO" (
  "ID" NUMBER,
  "TIPO_CUENTA" VARCHAR2(255),
  "MEDIO_PAGO_ID" NUMBER,
  "NUMERO_TARJETA" VARCHAR2(255),
  "BANCO" VARCHAR2(255),
  "CODIGO_SEGURIDAD" VARCHAR2(255),
  "EMAIL" VARCHAR2(255),
  "FECHA_EXPEDICION" DATE,
  "ENVIAR_CORREO" NUMBER(1),
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_TARJETA_MEDIO_PAGO_ID FOREIGN KEY (MEDIO_PAGO_ID) REFERENCES USUARIOS_MEDIOS_DE_PAGOS(ID)
);



CREATE TABLE "RECIBOS" (
  "ID" NUMBER,
  "FECHA" TIMESTAMP,
  "FACTURA_ID" NUMBER,
  "CLIENTE_ID" NUMBER,
  "CODIGO_PROMOCION_ID" NUMBER,
  "USUARIO_MEDIO_PAGO_ID" NUMBER,
  "MONEDA" VARCHAR2(255),
  "VALOR_COMISION" DECIMAL,
  "VALOR" DECIMAL,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_RECIBOS_FACTURA FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS(ID),
  CONSTRAINT FK_RECIBOS_CLIENTE_ID FOREIGN KEY (CLIENTE_ID) REFERENCES USUARIOS(ID),
  CONSTRAINT FK_RECIBOS_CODIGO_PROMOCION FOREIGN KEY (CODIGO_PROMOCION_ID) REFERENCES CODIGOS_PROMOCIONALES(ID),
  CONSTRAINT FK_USUARIO_MEDIO_PAGO FOREIGN KEY (USUARIO_MEDIO_PAGO_ID) REFERENCES USUARIOS_MEDIOS_DE_PAGOS(ID)
);



CREATE TABLE "DETALLES_FACTURAS" (
  "ID" NUMBER,
  "FACTURA_ID" NUMBER,
  "CONCEPTO" VARCHAR2(255),
  "VALOR" FLOAT,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS(ID)  
);

CREATE TABLE "PAGOS_CONDUCTOR" (
  "ID" NUMBER,
  "CONDUCTOR_ID" NUMBER, 
  "VALOR_A_PAGAR" DECIMAL,
  "FECHA_PAGO" TIMESTAMP,
  "CUENTA_BANCO" VARCHAR2(255),
  "FECHA_INICIO" DATE,
  "FECHA_FINAL" DATE,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_PAGOS_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE "DETALLE_PAGOS_CONDUCTOR" (
  "ID" NUMBER,
  "FACTURA_ID" NUMBER,
  "PAGOS_CONDUCTOR_ID" NUMBER,
  "VALOR" FLOAT,
  PRIMARY KEY ("ID"),
  CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS(ID),  
  CONSTRAINT FK_DETALLE_PAGOS_CONDUCTOR FOREIGN KEY (PAGOS_CONDUCTOR_ID) REFERENCES PAGOS_CONDUCTOR(ID)  
);



